version: "3.9"
services:
    trainer1:
        container_name: fl-trainer1
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6001"
          - "0"
          - "1"
        network_mode: "host"
    trainer2:
        container_name: fl-trainer2
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6002"
          - "1"
          - "1"
        network_mode: "host"
    trainer3:
        container_name: fl-trainer3
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6003"
          - "2"
          - "1"
        network_mode: "host"
    trainer4:
        container_name: fl-trainer4
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6004"
          - "3"
          - "1"
        network_mode: "host"
    trainer5:
        container_name: fl-trainer5
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6005"
          - "4"
          - "1"
        network_mode: "host"
    trainer6:
        container_name: fl-trainer6
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6006"
          - "5"
          - "1"
        network_mode: "host"
    trainer7:
        container_name: fl-trainer7
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6007"
          - "6"
          - "1"
        network_mode: "host"
    trainer8:
        container_name: fl-trainer8
        image: hmaid/hyperledger:dist-fed-core-fl
        tty: true
        stdin_open: true
        labels:
          service: trainer-core
        command:
          - "trainer"
          - "localhost"
          - "6008"
          - "7"
          - "1"
        network_mode: "host"