version: "3.9"
services:
  aggregatorOrg1:
    container_name: fl-aggregator.org1.example.com
    image: hmaid/hyperledger:dist-fed-core-fl
    tty: true
    stdin_open: true
    labels:
      service: aggregator-core
    command:
      - "aggregator"
      - "localhost"
      - "8091"
      - "0"
    network_mode: "host"
  aggregatorOrg2:
    container_name: fl-aggregator.org2.example.com
    image: hmaid/hyperledger:dist-fed-core-fl
    tty: true
    stdin_open: true
    labels:
      service: aggregator-core
    command:
        - "aggregator"
        - "localhost"
        - "8092"
        - "0"
    network_mode: "host"
  flAdmin:
    container_name: fl-flAdmin.org2.example.com
    image: hmaid/hyperledger:dist-fed-core-fl
    tty: true
    stdin_open: true
    labels:
      service: flAdmin-core
    command:
      - "flAdmin"
      - "localhost"
      - "8083"
      - "0"
    network_mode: "host"