# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninfo.proto\x12\x19\x63om.example.fljavagateway\"&\n\x05\x45vent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"Q\n\x0bModelSecret\x12\x0f\n\x07modelId\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\t\x12\x10\n\x08weights1\x18\x03 \x01(\x0c\x12\x10\n\x08weights2\x18\x04 \x01(\x0c\x62\x06proto3')



_EVENT = DESCRIPTOR.message_types_by_name['Event']
_MODELSECRET = DESCRIPTOR.message_types_by_name['ModelSecret']
Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:com.example.fljavagateway.Event)
  })
_sym_db.RegisterMessage(Event)

ModelSecret = _reflection.GeneratedProtocolMessageType('ModelSecret', (_message.Message,), {
  'DESCRIPTOR' : _MODELSECRET,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:com.example.fljavagateway.ModelSecret)
  })
_sym_db.RegisterMessage(ModelSecret)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENT._serialized_start=41
  _EVENT._serialized_end=79
  _MODELSECRET._serialized_start=81
  _MODELSECRET._serialized_end=162
# @@protoc_insertion_point(module_scope)